### ISSUE TITLE
Permit text-2.0

### ISSUE THREAD

**Issue by sjshuck** [stevenfontanella/microlens#154]
`microlens-platform` constrains `text` dependency to <1.3.  Glancing at the `microlens-platform` source, it doesn't seem like there's anything that would have to change to bump that constraint to <2.1, but I didn't try it.

Perhaps a revision is enough?

My motivation is that it currently blocks my tests from building against `text` 2.0: https://github.com/sjshuck/hs-pcre2/issues/25.

**Comment by stevenfontanella** [comment]
Hi Shlomo, thanks for reporting. I will check next week to confirm. I would suggest that you try building your project with `--allow-newer=text` and see if it works as expected. Feel free to send a PR with the version upgrade as well and I will be happy to look.

**Comment by sjshuck** [comment]
So I already have `allow-newer: true` in `stack.yaml` (it doesn't support specifying single dependencies).  I should have mentioned up front that it's only Cabal builds that are failing for me; I try to support them but for better or worse I'm pretty committed to the Stackage way of things.  I couldn't find an example of how to pass `--allow-newer` to `cabal` or `cabal.project` after a few minutes of looking so I gave up.

That said, doing complex dances to anticipate breaking changes in say `text` or `mtl` seem like they'd be easier in straight Cabal&mdash;this has been a learning experience for me 😛

**Comment by stevenfontanella** [comment]
For what it's worth, your stack builds are probably not breaking because you are using the [lts-19.8 resolver which uses text-1.2.5.0](https://www.stackage.org/lts-19.8/package/text-1.2.5.0). 

The command I meant is `cabal v2-build --allow-newer=text`. This will force cabal to allow a newer text version even if you have some dependencies with an upper bound that is too low (i.e. microlens requiring text < 2.0 in this case).

Thanks for sending the PR. I will merge it soon and create a new patch release.

**Comment by sjshuck** [comment]
> your stack builds

Hey, thanks for the help.  My stack builds are configured to use `text-2.0`, per `stack.yaml`.  I also have `allow-newer: true` set there, so `microlens-platform` is building without regard to upper bounds (`text` or anything else).  https://github.com/sjshuck/hs-pcre2/runs/6544741772?check_suite_focus=true

> `cabal v2-build`

Thanks again!

> I will merge it soon and create a new patch release.

Thanks yet again!
