### ISSUE TITLE
Operator cheatsheet

### ISSUE THREAD

**Issue by minad** [stevenfontanella/microlens#79]
Hi,

I like the minimal dependency approach of microlens, since I just started to use a lens library in Haskell. But I am wondering how you decide which operators to include and which not. For example I am missing ?=, which I expected to be there for consistency with ?~. It would also be great to have a complete list of all operators which shows if the operator exists in lens or microlens. Maybe you already have that written down somewhere since you derived the microlens design from lens?

And thx for the library!

**Comment by minad** [comment]
I know https://github.com/ekmett/lens/wiki/Operators, but it seems very incomplete. To find these many small functions I usually find the haddock documentation to scattered. Any recommendations?

**Comment by neongreen** [comment]
> But I am wondering how you decide which operators to include and which not.

Pretty much on an ad-hoc basis (when I or someone else needs something, I add it). For the same reason there is `mapAccumLOf` but no other `*Of` functions.

I don't like this approach, but at the same time I think it's the less of three evils (the other evils being “keep it consistent and small, refuse to make exceptions to satisfy actual users' needs” and “add things that users need, but also add lots of things that haven't been requested in order to preserve consistency”). The problem with consistency is that when there are several symmetrical functions/operators, it *does not* mean that they are used approximately as often.

I will add `?=` and make a release shortly (or you can add it by yourself, it's not hard!).

Regarding operator cheatsheets: I'm not aware of any that would include `?=` (which is kinda surprising). I should make one.

**Comment by neongreen** [comment]
There'll be one at guide.aelve.com (see https://github.com/aelve/guide/issues/101) at some point in the future; I'll ping you when it's done.

**Comment by minad** [comment]
good idea with guide. looking forward to it!

**Comment by neongreen** [comment]
Released microlens-mtl-0.1.9.

**Comment by minad** [comment]
:+1:

**Comment by neongreen** [comment]
hey hey hey, this issue ain't going nowhere until I've actually made a table :)

**Comment by minad** [comment]
Cool. Nice to know there is still activity. But I have to admit that I switched to lens by now.

**Comment by tebello-thejane** [comment]
Hmm...

Just as a quick anecdote, I very recently encountered this "issue" [when moving `pretty-simple` from `lens` to `microlens`](https://github.com/cdepillabout/pretty-simple/pull/11/commits/225ebfb81d1ff11c7f3eade35f6319f6573b803b#diff-612bebc9e81e2b7334f4a3faa48af844L83).

I have no idea what the `<>=` operator is supposed to do, exactly, but I was able to replace it by reading the `lens` source code. That is, `microlens`, even with its lack of `prism`s and such, *could* have included this operator with minimal fuss. I feel that `lens` contains a bit too many convenience functions and instances, and this, coupled with sometimes paltry documentation, makes the package a bit less usable than it should be.

So I'm all for only including those operators which users have asked for.

This is **not** a request for the inclusion of the `<>=` operator, though. ;-)

**Comment by minad** [comment]
Hi  @tebello-thejane,

I agree that it would be best if all operators which don't impose additional dependencies are included. However I also use Prisms and friends now.

Concerning pretty-simple, pretty-show etc, I recommend a [groom](https://hackage.haskell.org/package/groom-0.1.2/docs/src/Text-Groom.html) like approach coupled with hscolour :)

~~~ haskell
pshow :: (ConvertibleStrings String s, Show a) => a -> s
pshow = convertString . indent . show
  where indent s = case parseExp s of
                     ParseOk     e -> prettyPrint e
                     ParseFailed{} -> s

cshow :: (ConvertibleStrings String s, Show a) => a -> s
cshow = convertString . HsColour.hscolour HsColour.TTY
  HsColour.defaultColourPrefs True True "" False . pshow
~~~

**Comment by tebello-thejane** [comment]
A `groom` **like** approach?

I switched over from `groom` after I found out that, when stressed in a multithreading environment (producing the max amount of output in a busy infinite loop), it tended to randomly freeze the application for seconds at a time. I don't know if it's some threading issue or what. And since `groom` is a simple layer on top of the standard pretty print library, I fear this might be a bug there.

I can't think of how to produce a simple example reproducing this, but all I can say is that when I use plain `show` or `pretty-simple`, then the behaviour disappears...

Moreover, it produces ugly output with UUIDs and (IIRC) dates. Dates I can understand, since the `show` instance is non-compliant, but I can't fathom why UUIDs look like crap when they go through `groom`...

**Comment by tebello-thejane** [comment]
However, I will try out your snippet, @minad, and see if it's pretty and stable enough for me to use. Thanks! :-)

**Comment by minad** [comment]
good to know the downsides. thx!

**Comment by tebello-thejane** [comment]
Alas @minad: 
![image](https://cloud.githubusercontent.com/assets/7853189/22562533/98c62d1c-e985-11e6-8138-3b68c2242563.png)

Notice how `haskell-src-exts` inserts random spaces in the UUID, and `hscolour` uses colouring for `-` and lone digits, instead of treating the UUID as a string.

This is unusable.
